namespace PDIndexer;

// 260625Cl 自動生成 (tools/i18n_gen_dynamic.py 由来)。手で編集しない。
// 多言語化 Phase 2a: コード側で実行時に組み立てる動的 UI 文字列の 11 言語訳アクセサ。
// ボタン状態 (Find!/Stop! 等)・進捗フォーマット・MessageBox・日本語only の英語 canonical 化・
// 起動スプラッシュの永続表示。呼び出し側は PdiText.Xxx で参照し、{0}/{1} は string.Format で埋める。
internal static class PdiText
{
    /// <summary>Find (find)</summary>
    public static string Find => Crystallography.Localization.Loc(en: "Find!", ja: "検索!", de: "Suchen!", fr: "Trouver !", es: "¡Buscar!", pt: "Buscar!", it: "Trova!", ru: "Найти!", zhHans: "查找!", zhHant: "尋找!", ko: "찾기!");
    /// <summary>Stop (stop)</summary>
    public static string Stop => Crystallography.Localization.Loc(en: "Stop!", ja: "停止!", de: "Stopp!", fr: "Arrêter !", es: "¡Detener!", pt: "Parar!", it: "Stop!", ru: "Стоп!", zhHans: "停止!", zhHant: "停止!", ko: "정지!");
    /// <summary>Start (start)</summary>
    public static string Start => Crystallography.Localization.Loc(en: "Start", ja: "開始", de: "Start", fr: "Démarrer", es: "Iniciar", pt: "Iniciar", it: "Avvia", ru: "Старт", zhHans: "开始", zhHant: "開始", ko: "시작");
    /// <summary>Resume (resume)</summary>
    public static string Resume => Crystallography.Localization.Loc(en: "Resume", ja: "再開", de: "Fortsetzen", fr: "Reprendre", es: "Reanudar", pt: "Retomar", it: "Riprendi", ru: "Продолжить", zhHans: "继续", zhHant: "繼續", ko: "재개");
    /// <summary>TryNumber (tryNumber)</summary>
    public static string TryNumber => Crystallography.Localization.Loc(en: "Try Number: {0}", ja: "試行回数: {0}", de: "Versuch Nr.: {0}", fr: "Numéro d'essai : {0}", es: "Número de intento: {0}", pt: "Número da tentativa: {0}", it: "Numero di tentativo: {0}", ru: "Номер попытки: {0}", zhHans: "尝试次数: {0}", zhHant: "嘗試次數: {0}", ko: "시도 횟수: {0}");
    /// <summary>StepStat (stepStat)</summary>
    public static string StepStat => Crystallography.Localization.Loc(en: "total: {0} steps, {1} step/ms", ja: "合計: {0} steps, {1} step/ms", de: "Gesamt: {0} steps, {1} step/ms", fr: "total : {0} steps, {1} step/ms", es: "total: {0} steps, {1} step/ms", pt: "total: {0} steps, {1} step/ms", it: "totale: {0} steps, {1} step/ms", ru: "всего: {0} steps, {1} step/ms", zhHans: "总计: {0} steps, {1} step/ms", zhHant: "總計: {0} steps, {1} step/ms", ko: "합계: {0} steps, {1} step/ms");
    /// <summary>ClearCrystals (clearCrystals)</summary>
    public static string ClearCrystals => Crystallography.Localization.Loc(en: "Do you want to clear all crystals?", ja: "すべての結晶をクリアしますか?", de: "Möchten Sie alle Kristalle löschen?", fr: "Voulez-vous effacer tous les cristaux ?", es: "¿Desea borrar todos los cristales?", pt: "Deseja limpar todos os cristais?", it: "Vuoi eliminare tutti i cristalli?", ru: "Очистить все кристаллы?", zhHans: "是否清除所有晶体?", zhHant: "是否清除所有晶體?", ko: "모든 결정을 지우시겠습니까?");
    /// <summary>DeleteProfiles (deleteProfiles)</summary>
    public static string DeleteProfiles => Crystallography.Localization.Loc(en: "Do you want to delete all profiles?", ja: "すべてのプロファイルを削除しますか?", de: "Möchten Sie alle Profile löschen?", fr: "Voulez-vous supprimer tous les profils ?", es: "¿Desea eliminar todos los perfiles?", pt: "Deseja excluir todos os perfis?", it: "Vuoi eliminare tutti i profili?", ru: "Удалить все профили?", zhHans: "是否删除所有谱图?", zhHant: "是否刪除所有譜圖?", ko: "모든 프로파일을 삭제하시겠습니까?");
    /// <summary>ClipboardFail (clipboardFail)</summary>
    public static string ClipboardFail => Crystallography.Localization.Loc(en: "Failed to read clipboard information. Sorry.", ja: "クリップボードの情報の読み取りに失敗しました。申し訳ありません。", de: "Die Zwischenablage konnte nicht gelesen werden. Entschuldigung.", fr: "Échec de la lecture du presse-papiers. Désolé.", es: "No se pudo leer la información del portapapeles. Lo sentimos.", pt: "Falha ao ler as informações da área de transferência. Desculpe.", it: "Impossibile leggere le informazioni degli appunti. Spiacenti.", ru: "Не удалось прочитать данные буфера обмена. Извините.", zhHans: "读取剪贴板信息失败。抱歉。", zhHant: "讀取剪貼簿資訊失敗。抱歉。", ko: "클립보드 정보를 읽지 못했습니다. 죄송합니다.");
    /// <summary>MultiProfileSetting (multiProfileSetting)</summary>
    public static string MultiProfileSetting => Crystallography.Localization.Loc(en: "Now loading multiple profiles. Do you use this setting for the following profiles?", ja: "複数のプロファイルを読み込んでいます。この設定を以降のプロファイルにも使用しますか?", de: "Es werden mehrere Profile geladen. Möchten Sie diese Einstellung für die folgenden Profile verwenden?", fr: "Chargement de plusieurs profils en cours. Voulez-vous utiliser ce paramètre pour les profils suivants ?", es: "Cargando varios perfiles. ¿Desea utilizar esta configuración para los siguientes perfiles?", pt: "Carregando vários perfis. Deseja usar esta configuração para os perfis a seguir?", it: "Caricamento di più profili in corso. Vuoi usare questa impostazione per i profili seguenti?", ru: "Загружается несколько профилей. Использовать эту настройку для следующих профилей?", zhHans: "正在加载多个谱图。是否对以下谱图使用此设置?", zhHant: "正在載入多個譜圖。是否對以下譜圖使用此設定?", ko: "여러 프로파일을 불러오는 중입니다. 다음 프로파일에도 이 설정을 사용하시겠습니까?");
    /// <summary>MergeProfiles (mergeProfiles)</summary>
    public static string MergeProfiles => Crystallography.Localization.Loc(en: "Merge the profiles to one file? \r\n(if select No, each profiles will be saved separately \r\nwith the name of the input filename plus 'Profile Name'.)", ja: "プロファイルを1つのファイルに結合しますか? \r\n(いいえを選択すると、各プロファイルは入力ファイル名に 'Profile Name' を付けた名前で \r\n個別に保存されます。)", de: "Die Profile zu einer Datei zusammenführen? \r\n(Bei Auswahl von Nein wird jedes Profil separat \r\nmit dem Eingabedateinamen plus 'Profile Name' gespeichert.)", fr: "Fusionner les profils en un seul fichier ? \r\n(si vous choisissez Non, chaque profil sera enregistré séparément \r\nsous le nom du fichier d'entrée suivi de 'Profile Name'.)", es: "¿Combinar los perfiles en un solo archivo? \r\n(si selecciona No, cada perfil se guardará por separado \r\ncon el nombre del archivo de entrada más 'Profile Name'.)", pt: "Combinar os perfis em um único arquivo? \r\n(se selecionar Não, cada perfil será salvo separadamente \r\ncom o nome do arquivo de entrada mais 'Profile Name'.)", it: "Unire i profili in un unico file? \r\n(se selezioni No, ogni profilo verrà salvato separatamente \r\ncon il nome del file di input più 'Profile Name'.)", ru: "Объединить профили в один файл? \r\n(если выбрать Нет, каждый профиль будет сохранён отдельно \r\nс именем входного файла плюс 'Profile Name'.)", zhHans: "是否将谱图合并为一个文件? \r\n(若选择否,各谱图将以输入文件名加 'Profile Name' \r\n分别保存。)", zhHant: "是否將譜圖合併為一個檔案? \r\n(若選擇否,各譜圖將以輸入檔名加 'Profile Name' \r\n分別儲存。)", ko: "프로파일을 하나의 파일로 병합하시겠습니까? \r\n(아니요를 선택하면 각 프로파일은 입력 파일 이름에 'Profile Name'을 붙인 \r\n이름으로 개별 저장됩니다.)");
    /// <summary>DownloadFail (downloadFail)</summary>
    public static string DownloadFail => Crystallography.Localization.Loc(en: "Failed to download {0}. \r\nSorry!", ja: "{0} のダウンロードに失敗しました。 \r\n申し訳ありません!", de: "{0} konnte nicht heruntergeladen werden. \r\nEntschuldigung!", fr: "Échec du téléchargement de {0}. \r\nDésolé !", es: "No se pudo descargar {0}. \r\n¡Lo sentimos!", pt: "Falha ao baixar {0}. \r\nDesculpe!", it: "Impossibile scaricare {0}. \r\nSpiacenti!", ru: "Не удалось загрузить {0}. \r\nИзвините!", zhHans: "下载 {0} 失败。 \r\n抱歉!", zhHant: "下載 {0} 失敗。 \r\n抱歉!", ko: "{0} 다운로드에 실패했습니다. \r\n죄송합니다!");
    /// <summary>UpdateCheckFail (updateCheckFail)</summary>
    public static string UpdateCheckFail => Crystallography.Localization.Loc(en: "Failed update check. \r\nServer may be down. \r\nAccess {0}", ja: "更新の確認に失敗しました。 \r\nサーバーがダウンしている可能性があります。 \r\n{0} にアクセスしてください", de: "Update-Prüfung fehlgeschlagen. \r\nDer Server ist möglicherweise nicht erreichbar. \r\nRufen Sie {0} auf", fr: "Échec de la vérification des mises à jour. \r\nLe serveur est peut-être hors service. \r\nAccédez à {0}", es: "Error al comprobar las actualizaciones. \r\nEs posible que el servidor no esté disponible. \r\nAcceda a {0}", pt: "Falha na verificação de atualizações. \r\nO servidor pode estar fora do ar. \r\nAcesse {0}", it: "Controllo aggiornamenti non riuscito. \r\nIl server potrebbe non essere disponibile. \r\nVai a {0}", ru: "Не удалось проверить обновления. \r\nВозможно, сервер недоступен. \r\nПерейдите на {0}", zhHans: "更新检查失败。 \r\n服务器可能已停机。 \r\n请访问 {0}", zhHant: "更新檢查失敗。 \r\n伺服器可能已停機。 \r\n請存取 {0}", ko: "업데이트 확인에 실패했습니다. \r\n서버가 중단되었을 수 있습니다. \r\n{0}에 접속하세요");
    /// <summary>TitleWarning (titleWarning)</summary>
    public static string TitleWarning => Crystallography.Localization.Loc(en: "Warning", ja: "警告", de: "Warnung", fr: "Avertissement", es: "Advertencia", pt: "Aviso", it: "Avviso", ru: "Предупреждение", zhHans: "警告", zhHant: "警告", ko: "경고");
    /// <summary>TitleOption (titleOption)</summary>
    public static string TitleOption => Crystallography.Localization.Loc(en: "Option", ja: "オプション", de: "Option", fr: "Option", es: "Opción", pt: "Opção", it: "Opzione", ru: "Параметры", zhHans: "选项", zhHant: "選項", ko: "옵션");
    /// <summary>TitleExportOption (titleExportOption)</summary>
    public static string TitleExportOption => Crystallography.Localization.Loc(en: "Export option", ja: "エクスポートオプション", de: "Exportoption", fr: "Option d'exportation", es: "Opción de exportación", pt: "Opção de exportação", it: "Opzioni di esportazione", ru: "Параметры экспорта", zhHans: "导出选项", zhHant: "匯出選項", ko: "내보내기 옵션");
    /// <summary>TitleError (titleError)</summary>
    public static string TitleError => Crystallography.Localization.Loc(en: "Error", ja: "エラー", de: "Fehler", fr: "Erreur", es: "Error", pt: "Erro", it: "Errore", ru: "Ошибка", zhHans: "错误", zhHant: "錯誤", ko: "오류");
    /// <summary>TitleErrorBang (titleErrorBang)</summary>
    public static string TitleErrorBang => Crystallography.Localization.Loc(en: "Error!", ja: "エラー!", de: "Fehler!", fr: "Erreur !", es: "¡Error!", pt: "Erro!", it: "Errore!", ru: "Ошибка!", zhHans: "错误!", zhHant: "錯誤!", ko: "오류!");
    /// <summary>CannotWriteFile (cannotWriteFile)</summary>
    public static string CannotWriteFile => Crystallography.Localization.Loc(en: "Cannot write to file.", ja: "ファイルに書き込めません。", de: "Die Datei kann nicht geschrieben werden.", fr: "Impossible d'écrire dans le fichier.", es: "No se puede escribir en el archivo.", pt: "Não é possível gravar no arquivo.", it: "Impossibile scrivere sul file.", ru: "Не удалось записать в файл.", zhHans: "无法写入文件。", zhHant: "無法寫入檔案。", ko: "파일에 쓸 수 없습니다.");
    /// <summary>OpenFittingForm (openFittingForm)</summary>
    public static string OpenFittingForm => Crystallography.Localization.Loc(en: "Open the 'Fitting Diffraction Peak' form, check the peaks you want to analyze, then run.", ja: "'Fitting Diffraction Peak' フォームを開き、解析したいピークをチェックしてから実行してください。", de: "Öffnen Sie das Formular 'Fitting Diffraction Peak', markieren Sie die zu analysierenden Reflexe und führen Sie es dann aus.", fr: "Ouvrez le formulaire 'Fitting Diffraction Peak', cochez les pics à analyser, puis exécutez.", es: "Abra el formulario 'Fitting Diffraction Peak', marque los picos que desea analizar y luego ejecute.", pt: "Abra o formulário 'Fitting Diffraction Peak', marque os picos que deseja analisar e execute.", it: "Apri il modulo 'Fitting Diffraction Peak', seleziona i picchi da analizzare, quindi esegui.", ru: "Откройте форму 'Fitting Diffraction Peak', отметьте пики для анализа и запустите.", zhHans: "打开 'Fitting Diffraction Peak' 窗体,勾选要分析的峰,然后运行。", zhHant: "開啟 'Fitting Diffraction Peak' 視窗,勾選要分析的峰,然後執行。", ko: "'Fitting Diffraction Peak' 폼을 열고 분석할 피크를 체크한 후 실행하세요.");
    /// <summary>InitFinished (initFinished)</summary>
    public static string InitFinished => Crystallography.Localization.Loc(en: "Initializing has been finished successfully. You can close this window.", ja: "初期化が正常に完了しました。このウィンドウを閉じてかまいません。", de: "Die Initialisierung wurde erfolgreich abgeschlossen. Sie können dieses Fenster schließen.", fr: "L'initialisation s'est terminée avec succès. Vous pouvez fermer cette fenêtre.", es: "La inicialización se ha completado correctamente. Puede cerrar esta ventana.", pt: "A inicialização foi concluída com sucesso. Você pode fechar esta janela.", it: "L'inizializzazione è stata completata con successo. Puoi chiudere questa finestra.", ru: "Инициализация успешно завершена. Это окно можно закрыть.", zhHans: "初始化已成功完成。您可以关闭此窗口。", zhHant: "初始化已成功完成。您可以關閉此視窗。", ko: "초기화가 성공적으로 완료되었습니다. 이 창을 닫아도 됩니다.");
    /// <summary>InitLoadTime (initLoadTime)</summary>
    public static string InitLoadTime => Crystallography.Localization.Loc(en: "Initial loading time: {0} ms.", ja: "初回読み込み時間: {0} ms。", de: "Anfängliche Ladezeit: {0} ms.", fr: "Temps de chargement initial : {0} ms.", es: "Tiempo de carga inicial: {0} ms.", pt: "Tempo de carregamento inicial: {0} ms.", it: "Tempo di caricamento iniziale: {0} ms.", ru: "Время первоначальной загрузки: {0} ms.", zhHans: "初始加载时间: {0} ms。", zhHant: "初始載入時間: {0} ms。", ko: "초기 로딩 시간: {0} ms.");
    /// <summary>ShiftFunction (shiftFunction)</summary>
    public static string ShiftFunction => Crystallography.Localization.Loc(en: "Shift function: {0}", ja: "シフト関数: {0}", de: "Verschiebungsfunktion: {0}", fr: "Fonction de décalage : {0}", es: "Función de desplazamiento: {0}", pt: "Função de deslocamento: {0}", it: "Funzione di spostamento: {0}", ru: "Функция сдвига: {0}", zhHans: "平移函数: {0}", zhHant: "平移函數: {0}", ko: "이동 함수: {0}");
    /// <summary>NowCalibrating (nowCalibrating)</summary>
    public static string NowCalibrating => Crystallography.Localization.Loc(en: "Now calibrating...", ja: "校正中...", de: "Kalibrierung läuft...", fr: "Calibrage en cours...", es: "Calibrando...", pt: "Calibrando...", it: "Calibrazione in corso...", ru: "Калибровка...", zhHans: "正在校准...", zhHant: "正在校正...", ko: "보정 중...");
    /// <summary>Calibrate (calibrate)</summary>
    public static string Calibrate => Crystallography.Localization.Loc(en: "Calibrate", ja: "校正", de: "Kalibrieren", fr: "Calibrer", es: "Calibrar", pt: "Calibrar", it: "Calibra", ru: "Калибровать", zhHans: "校准", zhHant: "校正", ko: "보정");
    /// <summary>CalcTimePeakFitting (calcTimePeakFitting)</summary>
    public static string CalcTimePeakFitting => Crystallography.Localization.Loc(en: "Calculating Time (Peak Fitting) : {0}ms", ja: "計算時間 (ピークフィッティング) : {0}ms", de: "Berechnungszeit (Peak-Anpassung) : {0}ms", fr: "Temps de calcul (ajustement de pic) : {0}ms", es: "Tiempo de cálculo (ajuste de pico) : {0}ms", pt: "Tempo de cálculo (ajuste de pico) : {0}ms", it: "Tempo di calcolo (adattamento del picco) : {0}ms", ru: "Время вычисления (подгонка пика) : {0}ms", zhHans: "计算时间 (峰拟合) : {0}ms", zhHant: "計算時間 (峰擬合) : {0}ms", ko: "계산 시간 (피크 피팅) : {0}ms");
    /// <summary>CalculatingResidual (calculatingResidual)</summary>
    public static string CalculatingResidual => Crystallography.Localization.Loc(en: "Calculating ....  {0}", ja: "計算中 ....  {0}", de: "Berechnung ....  {0}", fr: "Calcul en cours ....  {0}", es: "Calculando ....  {0}", pt: "Calculando ....  {0}", it: "Calcolo in corso ....  {0}", ru: "Вычисление ....  {0}", zhHans: "正在计算 ....  {0}", zhHant: "正在計算 ....  {0}", ko: "계산 중 ....  {0}");
}
